# -*- coding: utf-8 -*-
"""Python_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lWU0w-TuEIX9HafG94_SxEsseHUypl9
"""

#Number Reduction Game
n=int(input())
step=0
while n!=1:
    if(n%2==0):
        n=n/2
        step+=1
    else:
        n=n*3+1
        step+=1
print(step)

list=[]
n=int(input("enter the n:"))
for i in range(0,n):
  m=int(input("number:"))
  list.append(m)
print(list)

#parking slot
l=[]
N=int(input())
for i in range(0,N):
  m=int(input())
  l.append(m)
Q=int(input())
for i in range(0,Q):
  str=input()
  if(str=="arrival"):
    for i in range(0,N):
      if(l[i]==0):
        if(l[i+1]==1 or l[i-1]==1):
          l[i]=1
          print(i+1)
          break
    print(l)

#List input
lst=list(map(int,input().split()))
print(lst)

